name: Build Server Docker Image

on:
  workflow_dispatch

jobs:
  package-server-jar:
    uses: CodeandoMexico/mapmap/.github/workflows/build-server-jar.yml@main
    
  docker-image-production:
    needs: package-server-jar
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Restore cached JAR
        id: cache-primes-restore
        uses: actions/cache/restore@v3
        with:
          path: mapmap-server.jar
          key: mapmap-server-jar

      - name: Build Docker Image
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: production
          image-tag: latest
          dockerfile: docker/Dockerfile
          build-context: .
