name: Docker Image

on:
    workflow_dispatch:
    push:
      branches:
        - main

jobs:
    package-server-app:
        runs-on: ubuntu-22.04
        environment: production
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                java-version: 17
                distribution: 'temurin'
                cache: maven
                server-id: github
                settings-path: ${{ github.workspace }}

            - name: Setup Maven
              uses: stCarolas/setup-maven@v4.5
              with:
                maven-version: 3.8.2

            - name: Package Jar
              run: mvn -f mapmap-server/pom.xml package -Dmaven.test.skip
            
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: mapmap-server
                path: mapmap-server/target/*.jar
                
            - name: Setup Maven settings.xml
              uses: whelk-io/maven-settings-xml-action@v11
              with:
              servers:
                '[
                  {
                    "id": "github",
                    "username": "${env.GITHUB_USERNAME}",
                    "password": "${env.GITHUB_TOKEN}"
                  }
                ]'

                
            - name: Publish to GitHub Packages Apache Maven
              run: mvn -f mapmap-server/pom.xml deploy -Dmaven.test.skip
              env:
                GITHUB_USERNAME: x-access-token
                GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
                BUILD_ENV: 'github-actions'
